import { Platform } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { Asset } from "expo-asset";
import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from "expo-audio";
import type { EffectKind, EffectSuit } from "@/lib/hitEffectsDiff";
import sfxZap from "../assets/sfx/zap.wav";
import sfxChime from "../assets/sfx/chime.wav";
import sfxShatter from "../assets/sfx/shatter.wav";
import sfxClang from "../assets/sfx/clang.wav";
import sfxStar from "../assets/sfx/star.wav";
import sfxAttack from "../assets/sfx/attack.wav";
import sfxDoom from "../assets/sfx/doom.wav";
import sfxDuelStart from "../assets/sfx/duel-start.wav";
import sfxDuelEnd from "../assets/sfx/duel-end.wav";
import sfxTurn from "../assets/sfx/turn.wav";
import sfxFanfare from "../assets/sfx/fanfare.wav";
import sfxDefeat from "../assets/sfx/defeat.wav";

// Game sounds. The WAVs are short synthesized one-shots generated by a script
// (license-free, ~15-50 KB each); swap the files for professional SFX any
// time without touching this module.
//
// Audio is decoration: every call is fail-safe (no-op on web, guarded on
// native) so a codec/session problem can never break gameplay. A persisted
// mute switch (toggled from the match menu) silences everything.
//
// Published-build gotcha: in a published (OTA/CDN) bundle, Metro asset ids
// resolve to extensionless hashed CDN URLs that the native audio player can
// fail to decode. We therefore resolve each asset through expo-asset first —
// `downloadAsync()` yields a `localUri` pointing at a cached file with a real
// `.wav` extension (and is a no-op for assets already bundled on disk) — and
// feed that URI to the player instead of the raw asset id.

const SUIT_SOURCES: Record<EffectSuit, number> = {
  C: sfxZap,
  H: sfxChime,
  D: sfxShatter,
  S: sfxClang,
  JOKER: sfxStar,
};

export type GameSfx = "attack" | "doom" | "duelStart" | "duelEnd" | "turn" | "fanfare" | "defeat";

const GAME_SOURCES: Record<GameSfx, number> = {
  attack: sfxAttack,
  doom: sfxDoom,
  duelStart: sfxDuelStart,
  duelEnd: sfxDuelEnd,
  turn: sfxTurn,
  fanfare: sfxFanfare,
  defeat: sfxDefeat,
};

const players = new Map<number, AudioPlayer>();
// One in-flight resolution per asset so concurrent plays don't double-create.
const pendingPlayers = new Map<number, Promise<AudioPlayer | null>>();
let audioModeSet = false;

function warn(context: string, err: unknown): void {
  if (__DEV__) console.warn(`[sfx] ${context}:`, err);
}

// ── Mute switch ──────────────────────────────────────────────────────────
const MUTE_KEY = "@mage/sfx-muted";
let muted = false;
let muteLoaded = false;

// Best-effort restore of the persisted preference; until it resolves the
// default (sound on) applies.
function loadMuteOnce(): void {
  if (muteLoaded) return;
  muteLoaded = true;
  AsyncStorage.getItem(MUTE_KEY)
    .then((v) => {
      if (v === "1") muted = true;
    })
    .catch((err) => warn("load mute preference", err));
}
loadMuteOnce();

export function getSfxMuted(): boolean {
  return muted;
}

export function setSfxMuted(m: boolean): void {
  muted = m;
  AsyncStorage.setItem(MUTE_KEY, m ? "1" : "0").catch((err) => warn("save mute preference", err));
}

// ── Playback ─────────────────────────────────────────────────────────────
function ensureAudioMode(): void {
  if (audioModeSet) return;
  audioModeSet = true;
  // Game feedback should be audible with the iOS mute switch on, and
  // should duck under (not pause) the user's music.
  setAudioModeAsync({ playsInSilentMode: true, interruptionMode: "mixWithOthers" }).catch((err) =>
    warn("set audio mode", err),
  );
}

/**
 * Resolve a Metro asset id to a playable player. In development the asset is
 * a dev-server URL with a `.wav` filename; in a published update it is an
 * extensionless hashed CDN URL, so we download it to the local asset cache
 * (which restores the extension) and play from `localUri`. Once created, a
 * player is cached for the whole app session.
 */
function getOrCreatePlayer(source: number): Promise<AudioPlayer | null> {
  const existing = players.get(source);
  if (existing) return Promise.resolve(existing);
  const pending = pendingPlayers.get(source);
  if (pending) return pending;

  const creation = (async (): Promise<AudioPlayer | null> => {
    try {
      const asset = Asset.fromModule(source);
      if (!asset.localUri) {
        await asset.downloadAsync();
      }
      const uri = asset.localUri ?? asset.uri;
      const player = createAudioPlayer({ uri });
      players.set(source, player);
      return player;
    } catch (err) {
      warn(`create player for asset ${source}`, err);
      return null;
    } finally {
      pendingPlayers.delete(source);
    }
  })();
  pendingPlayers.set(source, creation);
  return creation;
}

/**
 * Eagerly resolve every sound to a local file and create its player so first
 * plays are instant. Without this, a player is created on first use — and
 * that means the WAV is fetched (dev server or CDN) at that moment, which can
 * lag the sound seconds behind the action. Call once when the match screen
 * mounts; players persist for the whole app session.
 */
export function preloadSfx(): void {
  if (Platform.OS === "web") return;
  ensureAudioMode();
  for (const source of Object.values(SUIT_SOURCES)) void getOrCreatePlayer(source);
  for (const source of Object.values(GAME_SOURCES)) void getOrCreatePlayer(source);
}

function playSource(source: number, volume: number): void {
  if (Platform.OS === "web" || muted) return;
  ensureAudioMode();
  getOrCreatePlayer(source)
    .then((player) => {
      if (!player || muted) return;
      try {
        player.volume = volume;
        player.seekTo(0);
        player.play();
      } catch (err) {
        // Missing asset, dead audio session, etc. — skip the sound, keep playing.
        warn("play", err);
      }
    })
    .catch((err) => warn("play (resolve)", err));
}

/** Suit-flavored hit sound (zap/chime/shatter/clang/star). */
export function playSuitSfx(suit: EffectSuit, kind: EffectKind): void {
  playSource(SUIT_SOURCES[suit], kind === "destroy" ? 0.9 : 0.7);
}

/** Event sounds: royal death, duel start/end, your-turn, victory/defeat. */
export function playGameSfx(name: GameSfx): void {
  playSource(GAME_SOURCES[name], name === "turn" ? 0.6 : 0.85);
}
