import { Platform } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from "expo-audio";
import type { EffectKind, EffectSuit } from "@/lib/hitEffectsDiff";
import sfxZap from "../assets/sfx/zap.wav";
import sfxChime from "../assets/sfx/chime.wav";
import sfxShatter from "../assets/sfx/shatter.wav";
import sfxClang from "../assets/sfx/clang.wav";
import sfxStar from "../assets/sfx/star.wav";
import sfxAttack from "../assets/sfx/attack.wav";
import sfxDoom from "../assets/sfx/doom.wav";
import sfxDuelStart from "../assets/sfx/duel-start.wav";
import sfxDuelEnd from "../assets/sfx/duel-end.wav";
import sfxTurn from "../assets/sfx/turn.wav";
import sfxFanfare from "../assets/sfx/fanfare.wav";
import sfxDefeat from "../assets/sfx/defeat.wav";

// Game sounds. The WAVs are short synthesized one-shots generated by a script
// (license-free, ~15-50 KB each); swap the files for professional SFX any
// time without touching this module.
//
// Audio is decoration: every call is fail-safe (no-op on web, try/catch on
// native) so a codec/session problem can never break gameplay. A persisted
// mute switch (toggled from the match menu) silences everything.

const SUIT_SOURCES: Record<EffectSuit, number> = {
  C: sfxZap,
  H: sfxChime,
  D: sfxShatter,
  S: sfxClang,
  JOKER: sfxStar,
};

export type GameSfx = "attack" | "doom" | "duelStart" | "duelEnd" | "turn" | "fanfare" | "defeat";

const GAME_SOURCES: Record<GameSfx, number> = {
  attack: sfxAttack,
  doom: sfxDoom,
  duelStart: sfxDuelStart,
  duelEnd: sfxDuelEnd,
  turn: sfxTurn,
  fanfare: sfxFanfare,
  defeat: sfxDefeat,
};

const players = new Map<number, AudioPlayer>();
let audioModeSet = false;

// ── Mute switch ──────────────────────────────────────────────────────────
const MUTE_KEY = "@mage/sfx-muted";
let muted = false;
let muteLoaded = false;

// Best-effort restore of the persisted preference; until it resolves the
// default (sound on) applies.
function loadMuteOnce(): void {
  if (muteLoaded) return;
  muteLoaded = true;
  AsyncStorage.getItem(MUTE_KEY)
    .then((v) => {
      if (v === "1") muted = true;
    })
    .catch(() => {});
}
loadMuteOnce();

export function getSfxMuted(): boolean {
  return muted;
}

export function setSfxMuted(m: boolean): void {
  muted = m;
  AsyncStorage.setItem(MUTE_KEY, m ? "1" : "0").catch(() => {});
}

// ── Playback ─────────────────────────────────────────────────────────────
function playSource(source: number, volume: number): void {
  if (Platform.OS === "web" || muted) return;
  try {
    if (!audioModeSet) {
      audioModeSet = true;
      // Game feedback should be audible with the iOS mute switch on, and
      // should duck under (not pause) the user's music.
      setAudioModeAsync({ playsInSilentMode: true, interruptionMode: "mixWithOthers" }).catch(
        () => {},
      );
    }
    let player = players.get(source);
    if (!player) {
      player = createAudioPlayer(source);
      players.set(source, player);
    }
    player.volume = volume;
    player.seekTo(0);
    player.play();
  } catch {
    // Missing asset, dead audio session, etc. — skip the sound, keep playing.
  }
}

/** Suit-flavored hit sound (zap/chime/shatter/clang/star). */
export function playSuitSfx(suit: EffectSuit, kind: EffectKind): void {
  playSource(SUIT_SOURCES[suit], kind === "destroy" ? 0.9 : 0.7);
}

/** Event sounds: royal death, duel start/end, your-turn, victory/defeat. */
export function playGameSfx(name: GameSfx): void {
  playSource(GAME_SOURCES[name], name === "turn" ? 0.6 : 0.85);
}
