// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fun-ui/GameOver.tsx": () => import("../components/mockups/fun-ui/GameOver.tsx"),
  "./components/mockups/fun-ui/Lobby.tsx": () => import("../components/mockups/fun-ui/Lobby.tsx"),
  "./components/mockups/fun-ui/MatchHeader.tsx": () => import("../components/mockups/fun-ui/MatchHeader.tsx"),
  "./components/mockups/fun-ui/WaitingRoom.tsx": () => import("../components/mockups/fun-ui/WaitingRoom.tsx"),
  "./components/mockups/game-screen-variants/ArcaneManuscript.tsx": () => import("../components/mockups/game-screen-variants/ArcaneManuscript.tsx"),
  "./components/mockups/game-screen-variants/BrightTable.tsx": () => import("../components/mockups/game-screen-variants/BrightTable.tsx"),
  "./components/mockups/game-screen-variants/CommandHUD.tsx": () => import("../components/mockups/game-screen-variants/CommandHUD.tsx"),
  "./components/mockups/game-screen-variants/DuelSplit.tsx": () => import("../components/mockups/game-screen-variants/DuelSplit.tsx"),
  "./components/mockups/game-screen-variants/FocusMode.tsx": () => import("../components/mockups/game-screen-variants/FocusMode.tsx"),
  "./components/mockups/game-screen-variants/NestedArena.tsx": () => import("../components/mockups/game-screen-variants/NestedArena.tsx"),
  "./components/mockups/game-screen-variants/StorybookRealm.tsx": () => import("../components/mockups/game-screen-variants/StorybookRealm.tsx"),
  "./components/mockups/game-screen-variants/VoidNeon.tsx": () => import("../components/mockups/game-screen-variants/VoidNeon.tsx")
};
